spring:
  application:
    name: demo
  main:
    banner-mode: OFF
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: ${OLLAMA_MODEL}
logging:
  level:
    root: ERROR

